server:
  port: 80
  servlet:
    context-path: /blog


spring:
  redis:
    host: 121.36.54.216
    password: Wuniutech
    port: 6379
    database: 0
    connect-timeout: 60
  datasource:
    druid:
      url: jdbc:mysql://121.36.54.216:3306/blog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: blog
      password: ShenWenJie@2022
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 10
      max-wait: 60000
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher